Character fixes
jeffreykxiao/mukashi pull request #7
Opened 2018-09-04 23:21 UTC by imittongtare

- Character select displays properly.

2018-09-04 23:24 UTC, tphan020 approved these changes
Blueprints

2018-09-05 02:18 UTC, jeffreykxiao commented
@imittongtare do you think we can remove all the MobileStarterContent (maps and walls, etc)

2018-09-05 02:18 UTC, jeffreykxiao requested changes
Delete everything under MobileStarterContent/

2018-09-05 02:34 UTC, jeffreykxiao approved these changes

2018-09-05 02:34 UTC, merged